version: '3.7'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

  k6:
    image: grafana/k6
    container_name: k6
    depends_on:
      - influxdb
    volumes:
      - ./k6:/scripts
    entrypoint: [
      "k6", "run",
      "--out", "influxdb=http://influxdb:8086/k6",
      "/scripts/load_test.js"
    ]

volumes:
  influxdb:
  grafana-storage:
